"use client";

/**
 * ============ nav-icons.ts ============
 *
 * تبدیل «نام آیکون lucide» (رشته) به کامپوننت آیکون واقعی.
 * لازم است چون پیکربندی منوی کاربران از مرز سرور/کلاینت عبور می‌کند
 * (SystemSettings JSON → API → app-shell) و در JSON فقط نام رشته‌ای
 * قابل حمل است، نه کامپوننت React.
 *
 * استفاده: `const Icon = navIconByName("Wallet")` — با fallback امن.
 */

import {
  LayoutDashboard,
  Wallet,
  Users,
  MonitorSmartphone,
  Zap,
  Banknote,
  Sun,
  ShoppingCart,
  Store,
  Heart,
  Link2,
  Truck,
  Package,
  Briefcase,
  Receipt,
  Coins,
  BookOpen,
  CalendarRange,
  Building2,
  Landmark,
  Scale,
  Clock,
  BarChart3,
  FileText,
  FileCheck,
  ShieldCheck,
  Calendar,
  Gift,
  UserCircle,
  CreditCard,
  TrendingUp,
  CalendarClock,
  FileBarChart,
  Sparkles,
  Code2,
  ScrollText,
  KeyRound,
  Calculator,
  Globe,
  Smartphone,
  Headphones,
  Bug,
  Compass,
  Factory,
  HardHat,
  Star,
  Bell,
  Workflow,
  Mail,
  MessageSquare,
  AlertTriangle,
  Layers,
  Gauge,
  MessageCircle,
  Fingerprint,
  Webhook,
  PieChart,
  Tag,
  Network,
  ShoppingBag,
  Handshake,
  Boxes,
  GraduationCap,
  FlaskConical,
  NotebookPen,
  GitBranch,
  GitCompare,
  ExternalLink,
  Rocket,
  Target,
  Flag,
  Settings,
  Database,
  Server,
  Cloud,
  Home,
  Share2,
  Download,
  Upload,
  Crown,
  Megaphone,
  LifeBuoy,
  Bookmark,
  Filter,
  SlidersHorizontal,
  Circle,
  type LucideIcon,
} from "lucide-react";

/** نقشه نام → کامپوننت — هم‌عرض lib/nav-config.ts ICON_CHOICES */
export const NAV_ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Wallet,
  Users,
  MonitorSmartphone,
  Zap,
  Banknote,
  Sun,
  ShoppingCart,
  Store,
  Heart,
  Link2,
  Truck,
  Package,
  Briefcase,
  Receipt,
  Coins,
  BookOpen,
  CalendarRange,
  Building2,
  Landmark,
  Scale,
  Clock,
  BarChart3,
  FileText,
  FileCheck,
  ShieldCheck,
  Calendar,
  Gift,
  UserCircle,
  CreditCard,
  TrendingUp,
  CalendarClock,
  FileBarChart,
  Sparkles,
  Code2,
  ScrollText,
  KeyRound,
  Calculator,
  Globe,
  Smartphone,
  Headphones,
  Bug,
  Compass,
  Factory,
  HardHat,
  Star,
  Bell,
  Workflow,
  Mail,
  MessageSquare,
  AlertTriangle,
  Layers,
  Gauge,
  MessageCircle,
  Fingerprint,
  Webhook,
  PieChart,
  Tag,
  Network,
  ShoppingBag,
  Handshake,
  Boxes,
  GraduationCap,
  FlaskConical,
  NotebookPen,
  GitBranch,
  GitCompare,
  ExternalLink,
  Rocket,
  Target,
  Flag,
  Settings,
  Database,
  Server,
  Cloud,
  Home,
  Share2,
  Download,
  Upload,
  Crown,
  Megaphone,
  LifeBuoy,
  Bookmark,
  Filter,
  SlidersHorizontal,
  Circle,
};

/** پیش‌فرض ایمن وقتی نام آیکون ناشناخته باشد */
const FALLBACK_ICON: LucideIcon = Circle;

/**
 * تبدیل نام آیکون به کامپوننت — اگر نام نامعتبر/ناشناخته بود
 * آیکون دایرهٔ بی‌خطر برمی‌گردد (اپ هرگز نمی‌شکند).
 */
export function navIconByName(name: string | undefined | null): LucideIcon {
  if (!name) return FALLBACK_ICON;
  return NAV_ICON_MAP[name] ?? FALLBACK_ICON;
}
